[image-path]
dir = "~/github/screen/DATA/2025/10"
[image-path.taimee]
filename = '*_jp.co.taimee.png'
[ocr-filter.taimee]
heading = [0, 106, 196, -1]
shift = [219, 267, 345, 375]
breaktime = [488, 224, 0, -1]
paystub = [712, -1, 0, -1]
#heading = [0, 111, 196, -1]
#shift = [219, 267, 345, 373]
#breaktime = [488, 224, 0, 720]
#paystub = [714, -1, 0, -1]
