[image-path]
dir = "/home/yasukazu/Documents/screen/2025/09/png"
[image-aspect.taimee-test]
ratio = 1.1
# delta = 5
[image_area.taimee-test]
h_ratio = 0.125
[image_area.receiptocr_png]
size_wh = [720, 1612]
photo_xy = [42, 314, 674, 1226]