[image-path]
dir = "/home/yasukazu/Documents/screen/2025/09/png"
[image-aspect.taimee-test]
ratio = 1.1
# delta = 5
[image-area.taimee-test]
h_ratio = 0.125
h_exclude = 0.22 # crop out top 22%
[image-area.receiptocr_png]
size_wh = [720, 1612]
photo_xy = [42, 314, 674, 1226]